---
- name: install
  apt: name=nginx state=latest update_cache=true cache_valid_time=3600
  tags:
  - packages

- name: enable service
  service: name=nginx enabled=yes state=started
  notify: restart-nginx

- name: remove default conf
  file: state=absent path=/etc/nginx/conf.d/default.conf
  notify: reload-nginx

- name: remove default site conf
  file: path=/etc/nginx/conf.d/default state=absent
  notify: reload-nginx

- name: remove default site conf
  file: path=/etc/nginx/sites-available/default state=absent
  notify: reload-nginx

- name: add virtual host conf
  template: src=etc/nginx/conf.d/conf dest=/etc/nginx/conf.d/main.conf
  notify: restart-nginx
  when: is_vagrant is not defined

- name: add virtual host conf for vagrant (app_dev.php targeted instead of app_php)
  template: src=etc/nginx/conf.d/vagrantconf dest=/etc/nginx/conf.d/main.conf
  notify: restart-nginx
  when: is_vagrant is defined

- name: nginx - update mime types
  copy: src=etc/nginx/mime.types dest=/etc/nginx/mime.types owner=root group=root mode=0644
  notify: restart-nginx
